config/routes.rb
ActivitiesApp::Application.routes.draw do

  root :to => 'activities#index'

  resources :people
  get '/people/:id/show_all_deeds' => 'people#show_all_deeds'
  resources :activities
  resources :deeds
  resources :sessions, only: [:new, :create, :destroy]

  post '/signup' => 'people#new'
  match '/signin' => 'sessions#new', :via => [:put, :get]
  delete '/signout' => 'sessions#destroy'

  

end

app/models/action.rb
class Action < ActiveRecord::Base
  attr_accessible :activity_id, :person_id

  belongs_to :person
  belongs_to :activity
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	attr_accessible :name, :points, :category

	validates :name, presence: true, length: { maximum: 50 }, 
		uniqueness: { case_sensitive: false }
	validates :points, presence: true, 
		:numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
	validates :category, presence: true

	has_many :deeds, dependent: :destroy

  default_scope { order({category: :asc}, name: :asc) }

end

app/models/deed.rb
class Deed < ActiveRecord::Base
	attr_accessible :activity_id, :person_id, :points, :performed_at
  
  validates :performed_at, presence: true
  validates :points, presence: true, 
    numericality: { only_integer: true, greater_than: 0, less_than: 15 }
  
  default_scope { order(performed_at: :desc) }

	belongs_to :person
	belongs_to :activity

end

app/models/person.rb
class Person < ActiveRecord::Base
	attr_accessible :name, :password, :password_confirmation

	has_secure_password

	has_many :deeds, dependent: :destroy

	before_save :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }, 
		uniqueness: { case_sensitive: false }

	validates :password, presence: true, length: { minimum: 8 }

	validates :password_confirmation, presence: true, length: { minimum: 8 }

	private
	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end
	
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	before_filter :admin_user, only: [:create, :update, :destroy]

	def new
		@activity = Activity.new
	end

	def create
		@activity = Activity.new(params[:activity])
		if @activity.save
			flash[:success] = "New activity was successfully added."
			redirect_to @activity
		else
			render 'new'
		end
	end

	def index
		@activities = Activity.all
	end

	def show
		@activity = Activity.find(params[:id])
	end

	def edit
		@activity = Activity.find(params[:id])
	end

	def update
		@activity = Activity.find(params[:id])
		if @activity.update_attributes(params[:activity])
			flash[:success] = "Activity was successfully modified."
			redirect_to @activity
		else
			render 'edit'
		end
	end

	def destroy
		Activity.find(params[:id]).destroy
		flash[:success] = "Activity has been deleted."
		redirect_to activities_path
	end

	private
		def admin_user
			if ( !signed_in? || !current_person.admin )
				flash[:error] = "Operation failed. You must be signed in as an admin-level user to manage activities."
				redirect_to signin_path, notice: "Please sign in."
			end
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	include ApplicationHelper
end

app/controllers/deeds_controller.rb
class DeedsController < ApplicationController
	before_filter :signed_in_user, only: [:new, :create]
	before_filter :admin_user, only: [:edit, :update, :destroy]

	def new
		@deed = Deed.new(person_id: current_person.id)
	end

	def create
		@deed = Deed.new(params[:deed])
		@deed.points = @deed.activity.points
		@deed.performed_at = Time.now
		if @deed.save
			flash[:success] = "New deed was successfully added."
			# flash[:notice] = params
			redirect_to @deed.person
		else
			render 'new'
		end
	end

	def index
		@deeds = Deed.all
	end

	def show
		@deed = Deed.find(params[:id])
	end

	def edit
		@deed = Deed.find(params[:id])
	end

	def update
		@deed = Deed.find(params[:id])
		if @deed.update_attributes(params[:deed])
			flash[:success] = "Deed was successfully modified."
			redirect_to deeds_path
		else
			render 'edit'
		end
	end

	def destroy
		Deed.find(params[:id]).destroy
		flash[:success] = "Deed has been deleted."
		redirect_to deeds_path
	end

	private
		def signed_in_user
			if !signed_in?
				store_location
				redirect_to signin_path, notice: "Please sign in."
			end
		end

		def admin_user
			if !signed_in_as_admin?
				store_location
				flash[:error] = "Operation failed. You must be signed in as an admin-level user to manage deeds."
				redirect_to signin_path, notice: "Please sign in." 
			end
		end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	include ApplicationHelper

	before_filter :signed_in_user, only: [:edit, :update]
	before_filter :correct_user, only: [:edit, :update]

	def new
		@person = Person.new
	end

	def create
		if ( !signed_in? || !current_person.admin )
			flash[:error] = "Operation failed. You must be signed in as an admin-level user to manage people."
			redirect_to signin_path, notice: "Please sign in." 
		else
			@person = Person.new(params[:person])
			if @person.save
				flash[:success] = "New person was successfully added."
				flash[:notice] = params
				redirect_to @person
			else
				flash[:error] = "An error occurred when attempting to add a new person."
				render 'new'
			end
		end
	end

	def index
		@people = Person.order("name")
	end

	def show
		@person = Person.find(params[:id])
		date_range = Date.current.beginning_of_week...(Date.current + 1)
		@person_deeds_this_week = Deed.joins(:person).where(deeds: { created_at: date_range, person_id: params[:id] }).order("created_at desc")
	end

	def show_all_deeds
		@person = Person.find(params[:id])
		@person_deeds = @person.deeds.order("created_at desc")
		@person_deeds_count = @person.deeds.sum(:points)
	end

	def edit
		# no code needed because of before_filter :correct_user
	end

	def update
		# before_filter :correct_user finds the user
		if @person.update_attributes(params[:person])
			flash[:success] = "Person was successfully modified."
			redirect_to @person
		else
			render 'edit'
		end
	end

	def destroy
		@person = Person.find(params[:id])
		if !current_person.admin
			flash[:error] = "Operation failed. Only admin-level users are authorized to manage people. Sign in as an admin user and try again."
		else  # current person IS an admin, but:
			if current_person?(@person)
				flash[:error] = "You are not permitted to delete yourself!"
			else # current person is admin and you're not deleting yourself:
				@person.destroy
				flash[:success] = "Person has been deleted."
			end
		end
		redirect_to people_path
	end

	private
		def signed_in_user
			unless signed_in?
				store_location
				redirect_to signin_path, notice: "Please sign in."
			end
		end

		def correct_user
			@person = Person.find(params[:id])
			if ( !current_person?(@person) && !current_person.admin )
				flash[:error] = "You are not authorized to edit user #{@person.name}."
				redirect_to(root_path)
			end
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include ApplicationHelper

	def new
	end

	def create
		person = Person.where('lower(name) = ?', params[:session][:name].downcase).first
		if person && person.authenticate(params[:session][:password])
			sign_in(person)
			flash[:success] = "#{current_person.name} is now signed in."
			# redirect_to root_path
			redirect_back_or person
			
      # Sign the user in and redirect to the user's show page.
		else
			flash.now[:error] = 'Invalid name/password combination. Please try again.'
			render 'new'
		end
	end

	def destroy
		current_name = current_person.name
		sign_out
		flash[:success] = "#{current_name} was signed out successfully."
		redirect_back_or root_path
	end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sign_in(person)
		cookies.permanent[:remember_token] = person.remember_token
		self.current_person = person
	end

	def signed_in?
		!current_person.nil?
	end

	def current_person=(person)
		@current_person = person
	end

	def current_person
		@current_person ||= Person.find_by_remember_token(cookies[:remember_token])
	end

	def sign_out
		self.current_person = nil
		cookies.delete(:remember_token)
	end

	def current_person?(person)
		current_person == person
	end

	def signed_in_as_admin?
		signed_in? && current_person.admin
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || root_path)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.fullpath unless ( request.fullpath == "/signin" || request.fullpath == "/sessions" )
	end

end

app/helpers/deeds_helper.rb
module DeedsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/actions/index.html.erb
<% provide(:title, 'Show All Actions') %>
<h1>All Actions</h1>

<table cellpadding="5">
	<tr>
		<th>ID</th>
		<th>Person</th>
		<th>Activity</th>
		<th>Created</th>
		<th>Modified</th>
	</tr>

	<% @actions.each do |a| %>
	<tr>
		<td><%= a.id %></td>
		<td><%= link_to a.person.name, person_path(a.person.id) %></td>
		<td><%= link_to a.activity.name, activity_path(a.activity.id) %></td>
		<td><%= a.created_at %></td>
		<td><%= a.updated_at %></td>
		<td><%= link_to "Edit", edit_action_path(a.id) %></td>
		<td><%= link_to "Delete", @action, method: :delete, data: { confirm: "Are you sure?" } %></td>
	</tr>
	<% end %>

</table>

<br><a href="/actions/new">Add an action</a>

app/views/actions/show.html.erb
<% provide(:title, 'Show An Action') %>
<h1> This Action's Info:</h1>
<table cellpadding="5">
	<tr>
		<th>Person ID</th>
		<td><%= @action.person_id %></td>
	</tr>
	<tr>
		<th>Person Name</th>
		<td><%= @action.person.name %></td>
	</tr>
	<tr>
		<th>Activity ID</th>
		<td><%= @action.activity_id %></td>
	</tr>
	<tr>
		<th>Activity Name</th>
		<td><%= @action.activity.name %></td>
	</tr>
	<tr>
		<th>When Created</th>
		<td><%= @action.activity.created_at %></td>
	</tr>
</table>

<!-- The following block of code is commented out:  *********
<% if false %>
<h2>Times when <%= @action.name %> has been performed:
<!-- How to do a self-referential lookup (inner join with itself)?
		Would have to specify this in models/actions.rb then rake db?

<% if @action.SOMETHING.length == 0 %>
	None</h2>

<% else %>
	</h2>

	<table border="1">
		<tr>
			<th>ID</th>
			<th>Activity</th>
			<th>Created</th>
			<th>Modified</th>
		</tr>

		<% @action.actions.each do |p| %>
		<tr>
			<td><%= p.id %></td>
			<td><%= link_to p.activity.name, activity_path(p.activity.id) %></td>
			<td><%= p.created_at %></td>
			<td><%= p.updated_at %></td>
		</tr>
		<% end %>

	</table>
<% end %>
<% end %>
***** This is the end of the commented-out code -->

<br>
<a href="/actions">Show all actions</a> &nbsp; | &nbsp; <%= link_to "Delete this action", @action, method: :delete, data: { confirm: "Are you sure?" } %> &nbsp; | &nbsp; <%= link_to "Edit this action", edit_action_path(@action) %>

app/views/activities/edit.html.erb
<% provide(:title, 'Edit An Activity') %>

<h1>Edit an existing activity</h1>

<%= form_for(@activity) do |t| %>

	<%= render 'shared/error_messages', object_to_check:@activity %>

	<%= t.label :name %>
	<%= t.text_field :name %>

	<%= t.label :category %>
	<%= t.select :category, [['chore', 'chore'], ['physical', 'physical'], 
	['enrichment', 'enrichment']] %>

	<%= t.label :points %>
	<%= t.text_field :points %>

	<%= t.submit "Apply changes", class: "btn btn-large btn-primary" %>

<% end %>

app/views/activities/index.html.erb
<% provide(:title, 'Show All Activites') %>
<h1>List of All Activities</h1>

<table>
	<tr>
		<th class="left">Name</th>
		<th class="left">Category</th>
		<th>Points</th>
		<th># of Deeds</th>
		<% if signed_in_as_admin? %>
			<th>Created</th>
			<th>Modified</th>
			<th>ID</th>
		<% end %>
	</tr>

	<% @activities.each do |t| %>
	<tr>
		<td class="left"><%= link_to t.name, activity_path(t.id) %></td>
		<td class="left"><%= t.category %></td>
		<td><%= t.points %></td>
		<td><%= t.deeds.length %></td>
		<% if signed_in_as_admin? %>
			<td><%= t.created_at %></td>
			<td><%= t.updated_at %></td>
			<td><%= t.id %></td>
			<td><%= link_to "Edit", edit_activity_path(t.id) %></td>
			<td><%= link_to "Delete", t, method: :delete, data: { confirm: "Are you sure?" } %></td>
		<% end %>
	</tr>
	<% end %>

</table>

<br><a href="/people" class="click_link">Show all people</a>

<% if signed_in_as_admin? %>
	&nbsp; | &nbsp; 
	<a href="/activities/new" class="click_link">Create new activity</a>
<% end %>

app/views/activities/new.html.erb
<% provide(:title, 'Create An Activity') %>

<h1>Create a new activity</h1>

<%= form_for(@activity) do |t| %>

	<%= render 'shared/error_messages', object_to_check:@activity %>

	<%= t.label :name %>
	<%= t.text_field :name %>

	<%= t.label :category %>
	<%= t.select :category, [['chore', 'chore'], ['physical', 'physical'], 
	['enrichment', 'enrichment']] %>

	<%= t.label :points %>
	<%= t.text_field :points %>

	<%= t.submit "Create an activity", class: "btn btn-large btn-primary" %>

<% end %>

app/views/activities/show.html.erb
<% provide(:title, 'Show An Activity') %>
<h1><%= @activity.name %></h1>
<h2>Information for "<%= @activity.name %>":</h2>

<!-- <% @activity.attributes.to_options.to_a %> -->

<table>
	<tr>
		<% @activity.attributes.each do |a| %>
			<th><%= a[0] %></th>
		<% end %>
	</tr>
	
	<tr>
		<% @activity.attributes.each do |a| %>
			<td><%= a[1] %></td>
		<% end %>
	</tr>
</table>

<% if @activity.deeds.length == 0 %>
	<h2>No one has done activity "<%= @activity.name %>" yet.&nbsp;&nbsp;:(</h2>

<% else %>
	<h2>List of times activity "<%= @activity.name %>" has been performed:</h2>

	<table>
		<tr>
			<th>ID</th>
			<th>Person</th>
			<th>Created</th>
			<th>Modified</th>
		</tr>

		<% @activity.deeds.each do |a| %>
			<tr>
				<td><%= a.id %></td>
				<td><%= link_to a.person.name, person_path(a.person.id) %></td>
				<td><%= a.created_at.strftime("%d/%m/%y %H:%M") %></td>
				<td><%= a.updated_at.strftime("%d/%m/%y %H:%M") %></td>
			</tr>
		<% end %>

	</table>
<% end %>

<br>
<a href="/activities" class="click_link">Show all activities</a> &nbsp; | &nbsp; <%= link_to "Delete this activity", @activity, method: :delete, data: { confirm: "Are you sure?" } %> &nbsp; | &nbsp; <%= link_to "Edit this activity", edit_activity_path(@activity) %>

app/views/deeds/_deed_field.html.erb
	<% deed_field.hidden_field(:person_id) %>

	<%= deed_field.label "Activity" %>
	<%= deed_field.collection_select(:activity_id, Activity.all, :id, :name) %>
	
	<br><br>

app/views/deeds/index.html.erb
<% provide(:title, 'Show All Deeds') %>
<h1>All Deeds</h1>

<br><p><a href="/deeds/new" class="click_link">Add a deed</a></p>

<table>
	<tr>
		<th class="left person">Person</th>
		<th class="left">Activity</th>
		<th>Pts</th>
		<% if signed_in_as_admin? %>
			<th>ID</th>
			<th>Created</th>
			<th>Modified</th>
			<th>Performed at</th>
		<% else %>
			<th class="date">When</th>
		<% end %>
	</tr>

	<% @deeds.each do |a| %>
	<tr>
		<td class="left"><%= link_to a.person.name, person_path(a.person.id) %></td>
		<td class="left"><%= link_to a.activity.name, activity_path(a.activity.id) %></td>
		<td class="center"><%= a.points %></td>
		<% if signed_in_as_admin? %>
			<td><%= a.id %></td>
			<td><%= a.created_at %></td>
			<td><%= a.updated_at %></td>
			<td><%= if a.performed_at.present? then a.performed_at end %></td>
			<td><%= link_to "Edit", edit_deed_path(a.id) %></td>
			<td><%= link_to "Delete", a, method: :delete, data: { confirm: "Are you sure?" } %></td>
		<% else %>
			<td><%= a.performed_at %></td>
		<% end %>
	</tr>
	<% end %>

</table>

<br><a href="/deeds/new" class="click_link">Add a deed</a>

app/views/deeds/show.html.erb
<% provide(:title, 'Show A Deed') %>
<h1> This Deed's Info:</h1>
<table cellpadding="5">
	<tr>
		<th>Person ID</th>
		<td><%= @deed.person_id %></td>
	</tr>
	<tr>
		<th>Person Name</th>
		<td><%= @deed.person.name unless @deed.person.nil? %></td>
	</tr>
	<tr>
		<th>Activity ID</th>
		<td><%= @deed.activity_id %></td>
	</tr>
	<tr>
		<th>Activity Name</th>
		<td><%= @deed.activity.name unless @deed.activity.nil? %></td>
	</tr>
	<tr>
		<th>When Created</th>
		<td><%= @deed.activity.created_at unless @deed.activity.nil? %></td>
	</tr>
</table>

<!-- The following block of code is commented out:  *********
<% if false %>
<h2>Times when <%= @deed.name %> has been performed:
<!-- How to do a self-referential lookup (inner join with itself)?
		Would have to specify this in models/deeds.rb then rake db?

<% if @deed.SOMETHING.length == 0 %>
	None</h2>

<% else %>
	</h2>

	<table border="1">
		<tr>
			<th>ID</th>
			<th>Activity</th>
			<th>Created</th>
			<th>Modified</th>
		</tr>

		<% @deed.deeds.each do |p| %>
		<tr>
			<td><%= p.id %></td>
			<td><%= link_to p.activity.name, activity_path(p.activity.id) %></td>
			<td><%= p.created_at %></td>
			<td><%= p.updated_at %></td>
		</tr>
		<% end %>

	</table>
<% end %>
<% end %>
***** This is the end of the commented-out code -->

<br>
<a href="/deeds" class="click_link">Show all deeds</a>
<% if signed_in_as_admin? %>
	 &nbsp; | &nbsp; <%= link_to "Edit this deed", edit_deed_path(@deed) %> &nbsp; | &nbsp; <%= link_to "Delete this deed", @deed, method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Activities App", '#', id: "logo", class: "navbar-brand" %>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<li>
					<% if signed_in? %>
						<% store_location %>
						<%= link_to "Sign out", signout_path, method: "delete" %>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_person.name %>'s Account <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_person %></li> 
								<li><%= link_to "Settings", '#' %></li>
								<li class="divider"></li>
								<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
							</ul> 
						</li>
					<% elsif request.fullpath != "/signin" %>
						<% store_location %>
						<%= link_to "Sign in", signin_path %>
					<% end %>
				</li>
				<li><%= link_to "Home", 'people' %></li> 
			</ul>
		</div>
	</div>
</div>

app/views/layouts/_sidebar.html.erb
<ul class="nav nav-sidebar">
	<li><a href="/people">People</a></li>
	<li><a href="/deeds">Deeds</a></li>
	<li><a href="/activities">Activities</a></li>
</ul>

app/views/people/_person_deeds_list.html.erb
<% if person_deeds_list.length == 0 %>
	None</h2>

<% else %>
	</h2>

	<table>
		<tr>
			<th class="left">Activity</th>
			<th class="left">Pts</th>
			<% if signed_in_as_admin? %>
				<th>ID</th>
				<th>Created</th>
				<th>Modified</th>
				<th>Performed at</th>
			<% else %>
				<th class="date">When</th>
			<% end %>
		</tr>

		<% person_deeds_list.each do |p| %>
		<tr>
			<td class="left"><%= link_to p.activity.name, activity_path(p.activity.id) %></td>
			<td><%= p.points %></td>
			<% if signed_in_as_admin? %>
				<td><%= p.id %></td>
				<td><%= p.created_at %></td>
				<td><%= p.updated_at %></td>
				<td><%= if p.performed_at.present? then p.performed_at end %></td>
  			<td><%= link_to "Edit", edit_deed_path(p.id) %></td>
  			<td><%= link_to "Delete", p, method: :delete, data: { confirm: "Are you sure?" } %></td>
        
			<% else %>
				<td><%= if p.performed_at.present? then p.performed_at end %></td>
			<% end %>
		</tr>
		<% end %>

		<tr>
			<td><b>Total:</b></td>
			<td><b><%= person_deeds_list.reduce(0) {|sum, hash| sum + hash.points} %></b></td>
		</tr>

	</table>
<% end %>

<div class=".center">
<br><a href="/deeds/new" class="click_link">Add&nbsp;a&nbsp;deed</a>
<% if current_person?(@person) || signed_in_as_admin? %>
	&nbsp; | &nbsp; <%= link_to "Edit this person", edit_person_path(@person) %>
<% end %>
<% if signed_in_as_admin? %>
	&nbsp; | &nbsp; <%= link_to "Delete this person", @person, method: :delete, data: { confirm: "Are you sure?" } %> 
<% end %>

app/views/people/index.html.erb
<% provide(:title, 'Show All People') %>
<h1>List of All People</h1>

<table>
	<tr>
		<th class="left">Name</th>
		<th># of Deeds</th>
		<% if signed_in_as_admin? %>
			<th>ID</th>
			<th>Created</th>
			<th>Modified</th>
		<% end %>
	</tr>

	<% @people.each do |p| %>
	<tr>
		<td class="left">
			<% if current_person == p %>
				<b><%= link_to p.name, person_path(p.id) %> &nbsp;(me)</b>
			<% else %>
				<%= link_to p.name, person_path(p.id) %>
			<% end %>
		</td>
		<td><%= p.deeds.length %></td>
		<% if signed_in_as_admin? %>
			<td><%= p.id %></td>
			<td><%= p.created_at %></td>
			<td><%= p.updated_at %></td>
			<td><%= link_to "Edit", edit_person_path(p.id) %></td>
			<td><%= link_to "Delete", p, method: :delete, data: { confirm: "Are you sure?" } %></td>
		<% elsif current_person?(p) %>
			<td><%= link_to "Edit", edit_person_path(p.id) %></td>
		<% end %>
	</tr>
	<% end %>

</table>

<% if signed_in_as_admin? %>
	<br><a href="/people/new" class="click_link">Add a person</a>
<% end %>

app/views/people/show (backup).html.erb
<% provide(:title, @person.name) %>

<h1><%= @person.name %></h1>

<<<<<<< HEAD
<h2><%= @person.name %>'s deeds this week (from <%= Date.current.beginning_of_week.strftime("%d/%m/%y") %>):
=======
<h2>Deeds this week (from <%= Date.current.beginning_of_week.strftime("%d/%m/%y") %>):
>>>>>>> 650c26413440577fee424ff1c5e2fbad243a6d7e

<%= render 'people/person_deeds_list', person_deeds_list: @person_deeds_this_week %>

<<<<<<< HEAD
<% else %>
	</h2>

	<table>
		<tr>
			<th class="left">Activity</th>
			<th class="left">Points</th>
			<% if signed_in_as_admin? %>
				<th>ID</th>
				<th>Created</th>
				<th>Modified</th>
			<% else %>
				<th>When</th>
			<% end %>
		</tr>

		<% @person_deeds_this_week.each do |p| %>
		<tr>
			<td class="left"><%= link_to p.activity.name, activity_path(p.activity.id) %></td>
			<td><%= p.points %></td>
			<% if signed_in_as_admin? %>
				<td><%= p.id %></td>
				<td><%= p.created_at %></td>
				<td><%= p.updated_at %></td>
			<% else %>
				<td><%= p.created_at.strftime("%d/%m/%y %H:%M") %></td>
			<% end %>
		</tr>
		<% end %>

	</table>
<% end %>

<br><a href="/deeds/new" class="click_link">Add a deed</a>
<% if current_person?(@person) || signed_in_as_admin? %>
	&nbsp; | &nbsp; <%= link_to "Edit this person", edit_person_path(@person) %>
<% end %>
<% if signed_in_as_admin? %>
	&nbsp; | &nbsp; <%= link_to "Delete this person", @person, method: :delete, data: { confirm: "Are you sure?" } %> 
<% end %>
&nbsp; | &nbsp; <a href= <%= @person.id.to_s + "/show_all_deeds" %> >Show deed history</a>
=======
<a href= <%= @person.id.to_s + "/show_all_deeds" %> >Show deed history</a>
</div>
>>>>>>> 650c26413440577fee424ff1c5e2fbad243a6d7e

app/views/people/show_all_deeds (backup).html.erb
<% provide(:title, @person.name) %>
<<<<<<< HEAD
<h1><%= @person.name %></h1>

<h2><%= @person.name %>'s deed history:

<% if @person_deeds.length == 0 %>
	None</h2>

<% else %>
	</h2>

	<table>
		<tr>
			<th class="left">Activity</th>
			<% if signed_in_as_admin? %>
				<th>ID</th>
				<th>Created</th>
				<th>Modified</th>
			<% else %>
				<th>When</th>
			<% end %>
		</tr>

		<% @person_deeds.each do |p| %>
		<tr>
			<td class="left"><%= link_to p.activity.name, activity_path(p.activity.id) %></td>
			<% if signed_in_as_admin? %>
				<td><%= p.id %></td>
				<td><%= p.created_at %></td>
				<td><%= p.updated_at %></td>
			<% else %>
				<td><%= p.created_at.strftime("%d/%m/%y %H:%M") %></td>
			<% end %>
		</tr>
		<% end %>
=======

<h1><%= @person.name %></h1>

<h2>Deed history:
>>>>>>> 650c26413440577fee424ff1c5e2fbad243a6d7e

<%= render 'people/person_deeds_list', person_deeds_list: @person_deeds %>

<<<<<<< HEAD
<br><a href="/deeds/new" class="click_link">Add a deed</a>
<% if current_person?(@person) || signed_in_as_admin? %>
	&nbsp; | &nbsp; <%= link_to "Edit this person", edit_person_path(@person) %>
<% end %>
<% if signed_in_as_admin? %>
	&nbsp; | &nbsp; <%= link_to "Delete this person", @person, method: :delete, data: { confirm: "Are you sure?" } %> 
<% end %>
&nbsp; | &nbsp; <%= link_to "Show this week only", @person %>
=======
<%= link_to "Show this week only", @person %>
</div>
>>>>>>> 650c26413440577fee424ff1c5e2fbad243a6d7e